#!/bin/bash

# Dialed App - One-Command Setup
# Run this script to set up the Xcode project structure

echo "🏗️  Setting up Dialed Xcode project structure..."

# Get the directory where this script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

echo ""
echo "📋 SETUP INSTRUCTIONS:"
echo ""
echo "Since Xcode project files are complex binary/XML structures,"
echo "the easiest way to set this up is:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  Open Xcode"
echo ""
echo "2️⃣  File → New → Project"
echo "    • iOS → App"
echo "    • Product Name: Dialed"
echo "    • Interface: SwiftUI"
echo "    • Storage: None"
echo "    • Minimum Deployment: iOS 17.0"
echo ""
echo "3️⃣  Save to: $SCRIPT_DIR/DialedApp"
echo ""
echo "4️⃣  In Xcode, delete auto-generated files:"
echo "    • ContentView.swift"
echo "    • DialedApp.swift"
echo ""
echo "5️⃣  Drag folders from Finder into Xcode:"
echo "    From: $SCRIPT_DIR/Dialed/Dialed/"
echo "    Drag: App, Models, Services, Views, Utilities"
echo "    ☑️  Copy items if needed"
echo "    ☑️  Create groups"
echo ""
echo "6️⃣  Add HealthKit capability:"
echo "    • Project settings → Signing & Capabilities"
echo "    • + Capability → HealthKit"
echo ""
echo "7️⃣  Add to Info.plist:"
echo "    • Privacy - Health Share Usage Description"
echo "    • Value: (see Resources/Info.plist for text)"
echo ""
echo "8️⃣  Build (⌘B) and Run (⌘R) on a real device!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 For detailed step-by-step with screenshots, see:"
echo "   → QUICKSTART.md"
echo ""
echo "⚡ This takes about 5 minutes total."
echo ""
