//
//  NowNextStrip.swift
//  Dialed
//
//  The "Now / Next" panel that sits below the four state rings. Phase 3 will
//  replace the input source with real PlanBlocks generated by the planner;
//  for now we synthesize from the legacy ChecklistItem schedule so the screen
//  is real on day one.
//

import SwiftUI

/// Light-weight value type the strip renders. Decoupled from SwiftData so
/// previewing is cheap and the Phase 3 planner can produce these directly.
struct PlanBlockPresentation: Identifiable, Hashable {
    let id: UUID
    let title: String
    let subtitle: String?
    let time: Date
    let durationMinutes: Int?
    let icon: String
    let accent: [Color]
    let isCurrent: Bool

    init(
        id: UUID = UUID(),
        title: String,
        subtitle: String? = nil,
        time: Date,
        durationMinutes: Int? = nil,
        icon: String,
        accent: [Color],
        isCurrent: Bool = false
    ) {
        self.id = id
        self.title = title
        self.subtitle = subtitle
        self.time = time
        self.durationMinutes = durationMinutes
        self.icon = icon
        self.accent = accent
        self.isCurrent = isCurrent
    }
}

struct NowNextStrip: View {
    let current: PlanBlockPresentation?
    let upcoming: [PlanBlockPresentation]

    /// Drives the breathing pulse on the NOW beacon. Toggle continuously
    /// from onAppear so the outer ring scales + fades on a 1.4s loop.
    @State private var beaconPulse: Bool = false

    var body: some View {
        VStack(alignment: .leading, spacing: 14) {
            if let current {
                nowSection(current)
                Divider()
                    .background(Color.white.opacity(0.06))
            }

            nextSection
        }
        .padding(Spacing.md + 2)
        .background(
            RoundedRectangle(cornerRadius: Spacing.cardRadius, style: .continuous)
                .fill(.ultraThinMaterial)
                .overlay(
                    RoundedRectangle(cornerRadius: Spacing.cardRadius, style: .continuous)
                        .stroke(AppColors.glassStroke, lineWidth: 0.6)
                )
        )
        .onAppear {
            withAnimation(.easeInOut(duration: 1.4).repeatForever(autoreverses: true)) {
                beaconPulse = true
            }
        }
    }

    // MARK: - Sections

    private func nowSection(_ block: PlanBlockPresentation) -> some View {
        VStack(alignment: .leading, spacing: 10) {
            HStack(spacing: 8) {
                // Breathing "you are here" beacon.
                ZStack {
                    Circle()
                        .stroke(block.accent.first ?? .blue, lineWidth: 4)
                        .opacity(beaconPulse ? 0.0 : 0.45)
                        .scaleEffect(beaconPulse ? 2.6 : 1.0)
                        .frame(width: 6, height: 6)
                    Circle()
                        .fill(block.accent.first ?? .blue)
                        .frame(width: 6, height: 6)
                }
                Text("NOW")
                    .font(.system(size: 11, weight: .heavy, design: .rounded))
                    .tracking(1.4)
                    .foregroundColor(.white.opacity(0.6))
                Spacer()
                if let dur = block.durationMinutes {
                    Text(remainingLabel(for: block.time, duration: dur))
                        .font(.system(size: 11, weight: .semibold, design: .rounded))
                        .foregroundColor(.white.opacity(0.7))
                }
            }

            HStack(spacing: 14) {
                Image(systemName: block.icon)
                    .font(.system(size: 20, weight: .semibold))
                    .foregroundStyle(
                        LinearGradient(colors: block.accent, startPoint: .top, endPoint: .bottom)
                    )
                    .frame(width: 40, height: 40)
                    .background(
                        RoundedRectangle(cornerRadius: 12, style: .continuous)
                            .fill(block.accent.first?.opacity(0.16) ?? .clear)
                    )

                VStack(alignment: .leading, spacing: 2) {
                    Text(block.title)
                        .font(.system(size: 17, weight: .semibold))
                        .foregroundColor(.white)
                    if let subtitle = block.subtitle {
                        Text(subtitle)
                            .font(.system(size: 13))
                            .foregroundColor(.white.opacity(0.6))
                    }
                }

                Spacer()
            }
        }
    }

    private var nextSection: some View {
        VStack(alignment: .leading, spacing: 10) {
            Text("NEXT")
                .font(.system(size: 11, weight: .heavy, design: .rounded))
                .tracking(1.4)
                .foregroundColor(.white.opacity(0.55))

            if upcoming.isEmpty {
                HStack(spacing: 8) {
                    Image(systemName: "checkmark.seal.fill")
                        .font(.system(size: 16))
                        .foregroundColor(AppColors.Pillar.recovery.gradient.last)
                    Text("You're all clear for the rest of the day.")
                        .font(.system(size: 14))
                        .foregroundColor(.white.opacity(0.65))
                }
                .padding(.vertical, 4)
            } else {
                ForEach(upcoming) { block in
                    nextRow(block)
                }
            }
        }
    }

    private func nextRow(_ block: PlanBlockPresentation) -> some View {
        HStack(spacing: 14) {
            Text(Self.timeFormatter.string(from: block.time))
                .font(.system(size: 13, weight: .semibold, design: .rounded))
                .monospacedDigit()
                .foregroundColor(.white.opacity(0.85))
                .frame(width: 56, alignment: .leading)

            Image(systemName: block.icon)
                .font(.system(size: 13, weight: .medium))
                .foregroundStyle(
                    LinearGradient(colors: block.accent, startPoint: .top, endPoint: .bottom)
                )
                .frame(width: 22, height: 22)
                .background(
                    Circle().fill(block.accent.first?.opacity(0.14) ?? .clear)
                )

            VStack(alignment: .leading, spacing: 1) {
                Text(block.title)
                    .font(.system(size: 14, weight: .medium))
                    .foregroundColor(.white.opacity(0.92))
                if let subtitle = block.subtitle {
                    Text(subtitle)
                        .font(.system(size: 11))
                        .foregroundColor(.white.opacity(0.5))
                }
            }
            Spacer()
        }
        .padding(.vertical, 4)
    }

    // MARK: - Helpers

    private static let timeFormatter: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "h:mm a"
        return f
    }()

    private func remainingLabel(for start: Date, duration: Int) -> String {
        let end = start.addingTimeInterval(TimeInterval(duration * 60))
        let remaining = Int(end.timeIntervalSince(Date()) / 60)
        if remaining <= 0 {
            return "ends now"
        }
        if remaining < 60 {
            return "ends in \(remaining)m"
        }
        let h = remaining / 60
        let m = remaining % 60
        return m == 0 ? "ends in \(h)h" : "ends in \(h)h \(m)m"
    }
}

#Preview {
    let now = Date()
    let cal = Calendar.current
    ZStack {
        AppColors.nowBackground.ignoresSafeArea()
        NowNextStrip(
            current: PlanBlockPresentation(
                title: "Deep work",
                subtitle: "Focus block",
                time: now.addingTimeInterval(-1500),
                durationMinutes: 90,
                icon: "brain.head.profile",
                accent: AppColors.Pillar.readiness.gradient,
                isCurrent: true
            ),
            upcoming: [
                PlanBlockPresentation(
                    title: "Lunch + vitamins",
                    subtitle: "Protein target: 40g",
                    time: cal.date(byAdding: .hour, value: 1, to: now) ?? now,
                    icon: "fork.knife",
                    accent: AppColors.Pillar.energy.gradient
                ),
                PlanBlockPresentation(
                    title: "Push workout",
                    subtitle: "60m • Chest/shoulders",
                    time: cal.date(byAdding: .hour, value: 5, to: now) ?? now,
                    durationMinutes: 60,
                    icon: "figure.strengthtraining.traditional",
                    accent: AppColors.Pillar.strain.gradient
                ),
                PlanBlockPresentation(
                    title: "Wind down",
                    subtitle: "Skincare + screens off",
                    time: cal.date(byAdding: .hour, value: 10, to: now) ?? now,
                    icon: "moon.stars.fill",
                    accent: AppColors.Pillar.recovery.gradient
                )
            ]
        )
        .padding()
    }
    .preferredColorScheme(.dark)
}
