//
//  PlanView.swift
//  Dialed
//
//  The adaptive daily schedule. Loaded as the new "Plan" tab. Pulls from
//  DailyPlan (generated by PlanGenerator) — falls back to an on-demand
//  generation if today's plan hasn't been created yet.
//
//  Visual structure:
//    • Top bar: week strip (7 days) — tap to pivot
//    • Stats row: wake / sleep target / recovery used for anchoring
//    • Timeline: blocks grouped by day period (morning / midday / afternoon /
//      evening / night) — each block is a glass card with pillar accent,
//      status-aware styling, time, title, completion control
//

import SwiftUI
import SwiftData

struct PlanView: View {
    @Environment(\.modelContext) private var modelContext
    @StateObject private var viewModel = PlanViewModel()

    var body: some View {
        NavigationStack {
            ZStack {
                AppColors.nowBackground.ignoresSafeArea()

                ScrollView {
                    VStack(spacing: 22) {
                        weekStrip
                        anchorRow
                        timeline
                    }
                    .padding(.horizontal, 18)
                    .padding(.top, 8)
                    .padding(.bottom, 48)
                }
            }
            .navigationTitle("Plan")
            .navigationBarTitleDisplayMode(.large)
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button {
                        Task { await viewModel.regenerate(context: modelContext) }
                    } label: {
                        Image(systemName: "arrow.triangle.2.circlepath")
                            .font(.system(size: 15, weight: .semibold))
                            .foregroundColor(.white.opacity(0.75))
                    }
                }
            }
            .task { await viewModel.refresh(context: modelContext) }
            .refreshable { await viewModel.refresh(context: modelContext) }
        }
    }

    // MARK: - Week strip

    private var weekStrip: some View {
        HStack(spacing: 8) {
            ForEach(viewModel.weekDays, id: \.self) { date in
                weekDayCell(for: date)
            }
        }
        .padding(.horizontal, 4)
    }

    private func weekDayCell(for date: Date) -> some View {
        let isSelected = Calendar.current.isDate(date, inSameDayAs: viewModel.selectedDate)
        let isToday = Calendar.current.isDateInToday(date)
        let dayLetter = Self.weekdayLetter(date)
        let dayNumber = Calendar.current.component(.day, from: date)

        return Button {
            #if os(iOS)
            UIImpactFeedbackGenerator(style: .light).impactOccurred()
            #endif
            Task { await viewModel.select(date: date, context: modelContext) }
        } label: {
            VStack(spacing: 4) {
                Text(dayLetter)
                    .font(.system(size: 10, weight: .heavy, design: .rounded))
                    .tracking(1)
                    .foregroundColor(.white.opacity(isSelected ? 0.9 : 0.45))

                Text("\(dayNumber)")
                    .font(.system(size: 17, weight: .bold, design: .rounded))
                    .monospacedDigit()
                    .foregroundColor(isSelected ? .white : .white.opacity(isToday ? 0.85 : 0.55))

                Circle()
                    .fill(isToday ? AppColors.Pillar.readiness.gradient.last! : .clear)
                    .frame(width: 4, height: 4)
            }
            .frame(maxWidth: .infinity)
            .padding(.vertical, 10)
            .background(
                RoundedRectangle(cornerRadius: 16, style: .continuous)
                    .fill(isSelected
                          ? AppColors.Pillar.readiness.gradient.last!.opacity(0.22)
                          : Color.white.opacity(0.03))
                    .overlay(
                        RoundedRectangle(cornerRadius: 16, style: .continuous)
                            .stroke(isSelected
                                    ? AppColors.Pillar.readiness.gradient.last!.opacity(0.55)
                                    : AppColors.glassStroke,
                                    lineWidth: isSelected ? 1 : 0.5)
                    )
            )
        }
        .buttonStyle(.plain)
    }

    // MARK: - Anchor row (wake / sleep / recovery)

    private var anchorRow: some View {
        HStack(spacing: 12) {
            anchorTile(
                icon: "sun.max.fill",
                label: "Wake",
                value: viewModel.wakeAnchorLabel,
                gradient: AppColors.Pillar.energy.gradient
            )
            anchorTile(
                icon: "moon.stars.fill",
                label: "Sleep",
                value: viewModel.sleepAnchorLabel,
                gradient: AppColors.Pillar.recovery.gradient
            )
            anchorTile(
                icon: "leaf.fill",
                label: "Recovery",
                value: viewModel.recoveryLabel,
                gradient: AppColors.Pillar.recovery.gradient
            )
        }
    }

    private func anchorTile(icon: String, label: String, value: String, gradient: [Color]) -> some View {
        VStack(spacing: 6) {
            Image(systemName: icon)
                .font(.system(size: 14, weight: .semibold))
                .foregroundStyle(
                    LinearGradient(colors: gradient, startPoint: .top, endPoint: .bottom)
                )

            Text(value)
                .font(.system(size: 14, weight: .bold, design: .rounded))
                .monospacedDigit()
                .foregroundColor(.white)

            Text(label.uppercased())
                .font(.system(size: 9, weight: .heavy, design: .rounded))
                .tracking(1.2)
                .foregroundColor(.white.opacity(0.45))
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 14)
        .background(
            RoundedRectangle(cornerRadius: 18, style: .continuous)
                .fill(.ultraThinMaterial)
                .overlay(
                    RoundedRectangle(cornerRadius: 18, style: .continuous)
                        .stroke(AppColors.glassStroke, lineWidth: 0.5)
                )
        )
    }

    // MARK: - Timeline

    private var timeline: some View {
        VStack(spacing: 22) {
            if viewModel.groupedBlocks.isEmpty {
                emptyState
            } else {
                ForEach(viewModel.groupedBlocks, id: \.title) { group in
                    periodSection(group)
                }
            }
        }
    }

    private func periodSection(_ group: PlanViewModel.DayPeriodGroup) -> some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(spacing: 8) {
                Image(systemName: group.icon)
                    .font(.system(size: 11, weight: .semibold))
                    .foregroundColor(.white.opacity(0.55))
                Text(group.title.uppercased())
                    .font(.system(size: 11, weight: .heavy, design: .rounded))
                    .tracking(1.4)
                    .foregroundColor(.white.opacity(0.55))
                Spacer()
                Text(group.timeRange)
                    .font(.system(size: 11, weight: .medium, design: .rounded))
                    .foregroundColor(.white.opacity(0.35))
            }
            .padding(.horizontal, 6)

            VStack(spacing: 10) {
                ForEach(group.blocks, id: \.id) { item in
                    PlanBlockRow(
                        item: item,
                        onToggle: { Task { await viewModel.toggle(blockID: item.id, context: modelContext) } }
                    )
                }
            }
        }
    }

    private var emptyState: some View {
        VStack(spacing: 14) {
            Image(systemName: "calendar.badge.plus")
                .font(.system(size: 32, weight: .light))
                .foregroundColor(.white.opacity(0.35))

            Text("No plan for this day yet")
                .font(.system(size: 15, weight: .semibold))
                .foregroundColor(.white.opacity(0.8))

            Text("Tap regenerate to build a schedule from your weekly template.")
                .font(.system(size: 13))
                .foregroundColor(.white.opacity(0.5))
                .multilineTextAlignment(.center)
                .padding(.horizontal, 24)

            Button {
                Task { await viewModel.regenerate(context: modelContext) }
            } label: {
                Text("Generate plan")
                    .font(.system(size: 14, weight: .semibold, design: .rounded))
                    .foregroundColor(.white)
                    .padding(.horizontal, 22)
                    .padding(.vertical, 11)
                    .background(
                        Capsule()
                            .fill(
                                LinearGradient(
                                    colors: AppColors.Pillar.readiness.gradient,
                                    startPoint: .leading,
                                    endPoint: .trailing
                                )
                            )
                    )
            }
            .buttonStyle(.plain)
            .padding(.top, 4)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 40)
    }

    // MARK: - Helpers

    private static func weekdayLetter(_ date: Date) -> String {
        let f = DateFormatter()
        f.dateFormat = "EEE"
        return String(f.string(from: date).prefix(3)).uppercased()
    }
}

// MARK: - Block row

private struct PlanBlockRow: View {
    let item: PlanViewModel.BlockItem
    let onToggle: () -> Void

    var body: some View {
        HStack(spacing: 14) {
            // Time column
            VStack(alignment: .trailing, spacing: 1) {
                Text(item.timeLabel)
                    .font(.system(size: 13, weight: .semibold, design: .rounded))
                    .monospacedDigit()
                    .foregroundColor(.white.opacity(0.78))
                if let dur = item.durationLabel {
                    Text(dur)
                        .font(.system(size: 10, weight: .medium, design: .rounded))
                        .foregroundColor(.white.opacity(0.4))
                }
            }
            .frame(width: 56, alignment: .trailing)

            // Pillar-tinted icon disk
            ZStack {
                Circle()
                    .fill(item.pillar.gradient.first!.opacity(0.18))
                    .frame(width: 38, height: 38)
                Image(systemName: item.icon)
                    .font(.system(size: 15, weight: .semibold))
                    .foregroundStyle(
                        LinearGradient(
                            colors: item.pillar.gradient,
                            startPoint: .top,
                            endPoint: .bottom
                        )
                    )
            }

            // Title + subtitle
            VStack(alignment: .leading, spacing: 2) {
                Text(item.title)
                    .font(.system(size: 15, weight: .semibold))
                    .foregroundColor(.white.opacity(textOpacity))
                    .strikethrough(item.status == .done || item.status == .skipped, color: .white.opacity(0.5))
                if let subtitle = item.subtitle {
                    Text(subtitle)
                        .font(.system(size: 12))
                        .foregroundColor(.white.opacity(0.55))
                        .lineLimit(1)
                }
                if let skipNote = item.skipReason {
                    Text(skipNote)
                        .font(.system(size: 11, weight: .medium))
                        .foregroundColor(AppColors.warning.opacity(0.85))
                        .lineLimit(2)
                }
            }

            Spacer()

            // Status pill / completion toggle
            statusControl
        }
        .padding(.horizontal, 14)
        .padding(.vertical, 14)
        .background(
            RoundedRectangle(cornerRadius: 18, style: .continuous)
                .fill(cardFill)
                .overlay(
                    RoundedRectangle(cornerRadius: 18, style: .continuous)
                        .stroke(cardStroke, lineWidth: item.status == .active ? 1.1 : 0.5)
                )
        )
        .overlay(alignment: .leading) {
            // Subtle pillar-color accent stripe on the left edge.
            RoundedRectangle(cornerRadius: 2)
                .fill(
                    LinearGradient(colors: item.pillar.gradient, startPoint: .top, endPoint: .bottom)
                )
                .frame(width: 3)
                .padding(.vertical, 12)
                .opacity(item.status == .done || item.status == .skipped ? 0.25 : 0.85)
        }
    }

    private var textOpacity: Double {
        switch item.status {
        case .done, .skipped: return 0.45
        default: return 0.95
        }
    }

    private var cardFill: Material {
        item.status == .active ? .regularMaterial : .ultraThinMaterial
    }

    private var cardStroke: Color {
        switch item.status {
        case .active:
            return item.pillar.gradient.last!.opacity(0.55)
        default:
            return AppColors.glassStroke
        }
    }

    @ViewBuilder
    private var statusControl: some View {
        Button {
            #if os(iOS)
            UIImpactFeedbackGenerator(style: .medium).impactOccurred()
            #endif
            onToggle()
        } label: {
            switch item.status {
            case .done:
                Image(systemName: "checkmark.circle.fill")
                    .font(.system(size: 22, weight: .semibold))
                    .foregroundStyle(
                        LinearGradient(
                            colors: AppColors.Pillar.recovery.gradient,
                            startPoint: .top, endPoint: .bottom
                        )
                    )
            case .skipped:
                Image(systemName: "slash.circle.fill")
                    .font(.system(size: 22, weight: .semibold))
                    .foregroundColor(.white.opacity(0.35))
            case .active:
                ZStack {
                    Circle()
                        .stroke(item.pillar.gradient.last!.opacity(0.55), lineWidth: 1.5)
                        .frame(width: 22, height: 22)
                    Circle()
                        .fill(item.pillar.gradient.last!)
                        .frame(width: 8, height: 8)
                }
            case .due:
                Circle()
                    .stroke(AppColors.warning.opacity(0.8), lineWidth: 1.5)
                    .frame(width: 22, height: 22)
            case .upcoming:
                Circle()
                    .stroke(.white.opacity(0.25), lineWidth: 1.2)
                    .frame(width: 22, height: 22)
            }
        }
        .buttonStyle(.plain)
    }
}

#Preview {
    PlanView()
        .preferredColorScheme(.dark)
}
