//
//  DailyPlan.swift
//  Dialed
//
//  A concrete, wall-clock-resolved schedule for a single day. Generated by
//  PlanGenerator from the active WeeklyTemplate + the day's wake/sleep
//  anchors + current state. Re-generates each morning (or on demand).
//
//  Per-block status is tracked here, not on the template — the template is
//  a stable definition; completion state is daily.
//

import Foundation
import SwiftData

@Model
final class DailyPlan {
    @Attribute(.unique) var id: UUID

    /// The logical date this plan covers (start of day).
    var date: Date

    /// Which template produced this plan. Nil if user built it manually.
    var sourceTemplateID: UUID?

    /// The wake time the planner used to anchor `.afterWake` blocks.
    var anchorWakeTime: Date?
    /// The sleep-target time the planner used to anchor `.beforeSleep` blocks.
    var anchorSleepTime: Date?

    /// The recovery / readiness scores at generation time. Stored for
    /// transparency — explains why certain blocks may be missing.
    var generationRecovery: Int?
    var generationReadiness: Int?

    var generatedAt: Date

    /// Whether the user has manually edited blocks on this plan since
    /// generation. Manual edits are preserved on regenerate.
    var hasUserEdits: Bool

    @Relationship(deleteRule: .cascade, inverse: \PlanBlock.plan)
    var blocks: [PlanBlock]?

    init(
        date: Date,
        sourceTemplateID: UUID? = nil,
        anchorWakeTime: Date? = nil,
        anchorSleepTime: Date? = nil,
        generationRecovery: Int? = nil,
        generationReadiness: Int? = nil
    ) {
        self.id = UUID()
        self.date = Calendar.current.startOfDay(for: date)
        self.sourceTemplateID = sourceTemplateID
        self.anchorWakeTime = anchorWakeTime
        self.anchorSleepTime = anchorSleepTime
        self.generationRecovery = generationRecovery
        self.generationReadiness = generationReadiness
        self.generatedAt = Date()
        self.hasUserEdits = false
    }
}

@Model
final class PlanBlock {
    @Attribute(.unique) var id: UUID

    var plan: DailyPlan?

    /// Reference back to the template block that produced this — `nil` if
    /// the user created this block ad-hoc on a single day.
    var sourceTemplateBlockID: UUID?

    /// What kind of block — drives icon and styling.
    var kindRaw: String

    var title: String
    var blockDescription: String?

    /// Resolved wall-clock time this block starts.
    var startTime: Date
    var durationMinutes: Int

    var statusRaw: String
    var completedAt: Date?
    var skippedReason: String?

    /// User-typed override of the title/description on this specific day.
    var userEdited: Bool

    /// Optional ContextEvent id this block produced when completed —
    /// e.g. completing a "First coffee" block writes a caffeine event.
    var producedEventID: UUID?

    var createdAt: Date
    var updatedAt: Date

    init(
        kind: TemplateBlock.Kind,
        title: String,
        blockDescription: String? = nil,
        startTime: Date,
        durationMinutes: Int = 0,
        sourceTemplateBlockID: UUID? = nil
    ) {
        self.id = UUID()
        self.kindRaw = kind.rawValue
        self.title = title
        self.blockDescription = blockDescription
        self.startTime = startTime
        self.durationMinutes = durationMinutes
        self.statusRaw = Status.upcoming.rawValue
        self.userEdited = false
        self.sourceTemplateBlockID = sourceTemplateBlockID
        self.createdAt = Date()
        self.updatedAt = Date()
    }

    var kind: TemplateBlock.Kind {
        get { TemplateBlock.Kind(rawValue: kindRaw) ?? .routine }
        set { kindRaw = newValue.rawValue }
    }

    var status: Status {
        get { Status(rawValue: statusRaw) ?? .upcoming }
        set { statusRaw = newValue.rawValue }
    }

    var endTime: Date {
        startTime.addingTimeInterval(TimeInterval(durationMinutes * 60))
    }

    /// Computed "live" status — bumps `upcoming` → `active` once the start
    /// time passes and the block has a non-zero duration. Doesn't write back.
    func liveStatus(now: Date = Date()) -> Status {
        if status == .done || status == .skipped { return status }
        if durationMinutes > 0 && now >= startTime && now < endTime {
            return .active
        }
        if now >= startTime && durationMinutes == 0 {
            return .due
        }
        return .upcoming
    }

    /// Mark complete and stamp completion time.
    func markDone() {
        status = .done
        completedAt = Date()
        updatedAt = Date()
    }

    func markSkipped(reason: String? = nil) {
        status = .skipped
        skippedReason = reason
        updatedAt = Date()
    }
}

extension PlanBlock {
    enum Status: String, Codable {
        case upcoming    // hasn't started yet
        case due         // moment-in-time block whose start has passed but isn't done
        case active      // duration block currently in progress
        case done        // completed
        case skipped     // explicitly skipped (or auto-skipped by min-recovery filter)
    }
}
